packages:
  - packages/*

catalog:
  '@eslint/js': ^9.39.2
  '@jest/globals': ^30.2.0
  '@swc/jest': ^0.2.39
  '@types/node': ^20.19.27
  '@types/prompts': ^2.4.9
  '@types/semver': ^7.7.1
  chalk: ^5.6.2
  concurrently: ^9.2.1
  effect: ^3.19.14
  eslint: ^9.39.2
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jest: ^29.12.1
  eslint-plugin-prettier: ^5.5.4
  globals: ^17.0.0
  husky: ^9.1.7
  jest: ^30.2.0
  lint-staged: ^16.2.7
  neverthrow: ^8.2.0
  prettier: 3.7.4
  prompts: ^2.4.2
  rimraf: ^6.1.2
  semver: ^7.7.3
  serializr: ^3.0.2
  tinybench: ^6.0.0
  typeorm: ^0.3.0
  typescript: 5.9.3
  typescript-eslint: ^8.53.1

catalogMode: prefer

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'

publicHoistPattern:
  - '*eslint*'

workspaceConcurrency: 0
