name: Release

on:
  push:
    tags:
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-alpha'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-beta'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-rc'
      - '@rustresult/*_v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Publish
        run: node scripts/release.mjs
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
